import Navbar from "./navbar";

export const metadata = {
  title: "Sistem Pencatatan Produksi Beras",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  
  return (
    <>
      {/* main body */}
      <div className="flex h-full bg-gray-100 overflow-auto">
        {/* sidebar */}
        <Navbar />
        {/* content */}
        <main className="w-full md:ml-60 md:p-6 overflow-auto">
            {/* children */}
            {children}
        </main>
      </div>
    </>
  );
}
